// Fake data for the application

export const users = [
  {
    id: "1",
    email: "yunusemre@gmail.com",
    name: "Yunus Emre",
    surname: "Mert",
    phone: "5308808637",
    birthDate: "1990-06-15",
    occupation: "Yazılım Geliştirici",
    smsConsent: true,
    emailConsent: false,
    phoneConsent: true,
    password: "123456", // In a real app, this would be hashed
  },
]

export const categories = [
  {
    id: "1",
    name: "Pizzalar",
    description: "Taze ve lezzetli pizzalarımız",
    image: "/placeholder.svg?height=200&width=200",
    sortOrder: 1,
  },
  {
    id: "2",
    name: "İçecekler",
    description: "Serinletici içecekler",
    image: "/placeholder.svg?height=200&width=200",
    sortOrder: 2,
  },
  {
    id: "3",
    name: "Ekstralar",
    description: "Lezzetli yan ürünler",
    image: "/placeholder.svg?height=200&width=200",
    sortOrder: 3,
  },
]

export const products = [
  // Pizzas
  {
    id: "1",
    name: "Margarita Pizza",
    description: "Domates sosu, mozzarella peyniri, fesleğen",
    price: 180,
    originalPrice: null,
    image: "/placeholder.svg?height=200&width=200",
    isActive: true,
    isFeatured: true,
    categoryId: "1",
    sizes: ["Küçük", "Orta", "Büyük", "X-Large"],
    ingredients: ["Domates Sosu", "Mozzarella", "Fesleğen"],
    badges: [],
  },
  {
    id: "2",
    name: "Pepperoni Pizza",
    description: "Domates sosu, mozzarella, pepperoni",
    price: 220,
    originalPrice: null,
    image: "/placeholder.svg?height=200&width=200",
    isActive: true,
    isFeatured: false,
    categoryId: "1",
    sizes: ["Küçük", "Orta", "Büyük", "X-Large"],
    ingredients: ["Domates Sosu", "Mozzarella", "Pepperoni"],
    badges: [],
  },
  {
    id: "3",
    name: "Karışık Pizza",
    description: "Domates sosu, mozzarella, sucuk, salam, mantar",
    price: 250,
    originalPrice: null,
    image: "/placeholder.svg?height=200&width=200",
    isActive: true,
    isFeatured: true,
    categoryId: "1",
    sizes: ["Küçük", "Orta", "Büyük", "X-Large"],
    ingredients: ["Domates Sosu", "Mozzarella", "Sucuk", "Salam", "Mantar"],
    badges: [],
  },
  {
    id: "4",
    name: "Vejeteryan Pizza",
    description: "Domates sosu, mozzarella, sebzeler",
    price: 200,
    originalPrice: null,
    image: "/placeholder.svg?height=200&width=200",
    isActive: true,
    isFeatured: false,
    categoryId: "1",
    sizes: ["Küçük", "Orta", "Büyük", "X-Large"],
    ingredients: ["Domates Sosu", "Mozzarella", "Biber", "Mantar", "Zeytin"],
    badges: [],
  },
  {
    id: "5",
    name: "Ton Balıklı Pizza",
    description: "Domates sosu, mozzarella, ton balığı, soğan",
    price: 240,
    originalPrice: null,
    image: "/placeholder.svg?height=200&width=200",
    isActive: true,
    isFeatured: true,
    categoryId: "1",
    sizes: ["Küçük", "Orta", "Büyük", "X-Large"],
    ingredients: ["Domates Sosu", "Mozzarella", "Ton Balığı", "Soğan"],
    badges: [],
  },
  {
    id: "6",
    name: "Sucuklu Pizza",
    description: "Domates sosu, mozzarella, sucuk",
    price: 210,
    originalPrice: null,
    image: "/placeholder.svg?height=200&width=200",
    isActive: true,
    isFeatured: false,
    categoryId: "1",
    sizes: ["Küçük", "Orta", "Büyük", "X-Large"],
    ingredients: ["Domates Sosu", "Mozzarella", "Sucuk"],
    badges: [],
  },

  // Drinks
  {
    id: "7",
    name: "Coca Cola 1L",
    description: "Soğuk ve ferahlatıcı",
    price: 25,
    originalPrice: null,
    image: "/placeholder.svg?height=200&width=200",
    isActive: true,
    isFeatured: false,
    categoryId: "2",
    sizes: ["1L"],
    ingredients: [],
    badges: [],
  },
  {
    id: "8",
    name: "Fanta 1L",
    description: "Portakal aromalı",
    price: 25,
    originalPrice: null,
    image: "/placeholder.svg?height=200&width=200",
    isActive: true,
    isFeatured: false,
    categoryId: "2",
    sizes: ["1L"],
    ingredients: [],
    badges: [],
  },
  {
    id: "9",
    name: "Sprite 1L",
    description: "Limon aromalı",
    price: 25,
    originalPrice: null,
    image: "/placeholder.svg?height=200&width=200",
    isActive: true,
    isFeatured: false,
    categoryId: "2",
    sizes: ["1L"],
    ingredients: [],
    badges: [],
  },
  {
    id: "10",
    name: "Su 0.5L",
    description: "Doğal kaynak suyu",
    price: 8,
    originalPrice: null,
    image: "/placeholder.svg?height=200&width=200",
    isActive: true,
    isFeatured: false,
    categoryId: "2",
    sizes: ["0.5L"],
    ingredients: [],
    badges: [],
  },
  {
    id: "11",
    name: "Ayran 250ml",
    description: "Geleneksel Türk içeceği",
    price: 12,
    originalPrice: null,
    image: "/placeholder.svg?height=200&width=200",
    isActive: true,
    isFeatured: false,
    categoryId: "2",
    sizes: ["250ml"],
    ingredients: [],
    badges: [],
  },

  // Extras
  {
    id: "12",
    name: "Garlic Bread",
    description: "Sarımsaklı ekmek",
    price: 35,
    originalPrice: null,
    image: "/placeholder.svg?height=200&width=200",
    isActive: true,
    isFeatured: false,
    categoryId: "3",
    sizes: ["Orta"],
    ingredients: [],
    badges: [],
  },
  {
    id: "13",
    name: "Chicken Wings",
    description: "Baharatlı tavuk kanatları",
    price: 45,
    originalPrice: null,
    image: "/placeholder.svg?height=200&width=200",
    isActive: true,
    isFeatured: false,
    categoryId: "3",
    sizes: ["6 Adet", "12 Adet"],
    ingredients: [],
    badges: [],
  },
  {
    id: "14",
    name: "Patates Kızartması",
    description: "Çıtır çıtır patates",
    price: 30,
    originalPrice: null,
    image: "/placeholder.svg?height=200&width=200",
    isActive: true,
    isFeatured: false,
    categoryId: "3",
    sizes: ["Küçük", "Orta", "Büyük"],
    ingredients: [],
    badges: [],
  },
]

export const campaigns = [
  {
    id: "1",
    title: "2 Orta Boy Süperix veya Margarita",
    description: "Adabella Pizza'dan lezzetli kampanyalar!",
    image: "/placeholder.svg?height=400&width=800",
    price: 350,
    originalPrice: 450,
    badge: "YENİ",
    isActive: true,
    startDate: "2024-01-01",
    endDate: "2024-12-31",
  },
  {
    id: "2",
    title: "2 Orta Boy Pan Cazip Pizzalar",
    description: "Pan pizza lezzeti",
    image: "/placeholder.svg?height=400&width=800",
    price: 390,
    originalPrice: 500,
    badge: "PAN150",
    isActive: true,
    startDate: "2024-01-01",
    endDate: "2024-12-31",
  },
  {
    id: "3",
    title: "Pizza X-Large Süperix veya Margarita",
    description: "Büyük boy lezzet",
    image: "/placeholder.svg?height=400&width=800",
    price: 320,
    originalPrice: 420,
    badge: null,
    isActive: true,
    startDate: "2024-01-01",
    endDate: "2024-12-31",
  },
  {
    id: "4",
    title: "2 Orta Boy Bol Pan Pizza",
    description: "Bol malzemeli pan pizza",
    image: "/placeholder.svg?height=400&width=800",
    price: 440,
    originalPrice: 580,
    badge: "YENİ",
    isActive: true,
    startDate: "2024-01-01",
    endDate: "2024-12-31",
  },
  {
    id: "5",
    title: "Büyük Boy Süperix veya Margarita",
    description: "Tek kişilik lezzet",
    image: "/placeholder.svg?height=400&width=800",
    price: 270,
    originalPrice: 350,
    badge: null,
    isActive: true,
    startDate: "2024-01-01",
    endDate: "2024-12-31",
  },
  {
    id: "6",
    title: "3 Orta Boy Karışık Pizza",
    description: "Arkadaşlarla paylaşım",
    image: "/placeholder.svg?height=400&width=800",
    price: 580,
    originalPrice: 720,
    badge: "SÜPER FİYAT",
    isActive: true,
    startDate: "2024-01-01",
    endDate: "2024-12-31",
  },
]

export const addresses = [
  {
    id: "1",
    userId: "1",
    title: "Ev",
    fullAddress: "Güvercintepe Mah. Örnek Sok. No:15 Daire:3",
    district: "Başakşehir",
    city: "İstanbul",
    postalCode: "34480",
    isDefault: true,
  },
]

export const creditCards = [
  {
    id: "1",
    userId: "1",
    name: "Kişisel Kartım",
    cardNumber: "**** **** **** 1234",
    cardType: "Visa",
    expiryMonth: 12,
    expiryYear: 2026,
    holderName: "YUNUS EMRE MERT",
    isDefault: true,
  },
  {
    id: "2",
    userId: "1",
    name: "İş Kartım",
    cardNumber: "**** **** **** 5678",
    cardType: "Mastercard",
    expiryMonth: 8,
    expiryYear: 2025,
    holderName: "YUNUS EMRE MERT",
    isDefault: false,
  },
]

export const orders = [
  {
    id: "1",
    orderNumber: "ADL-2024-001",
    userId: "1",
    status: "DELIVERED",
    totalAmount: 285,
    deliveryFee: 15,
    discountAmount: 0,
    paymentMethod: "Kredi Kartı",
    notes: null,
    estimatedTime: 30,
    addressId: "1",
    createdAt: "2024-01-15T19:30:00Z",
    updatedAt: "2024-01-15T20:05:00Z",
    items: [
      {
        id: "1",
        orderId: "1",
        productId: "1",
        quantity: 2,
        size: "Orta",
        price: 180,
        notes: null,
      },
      {
        id: "2",
        orderId: "1",
        productId: "7",
        quantity: 1,
        size: "1L",
        price: 25,
        notes: null,
      },
      {
        id: "3",
        orderId: "1",
        productId: "12",
        quantity: 1,
        size: "Orta",
        price: 35,
        notes: null,
      },
    ],
    tracking: [
      {
        id: "1",
        orderId: "1",
        status: "CONFIRMED",
        message: "Sipariş alındı",
        timestamp: "2024-01-15T19:30:00Z",
      },
      {
        id: "2",
        orderId: "1",
        status: "PREPARING",
        message: "Hazırlanıyor",
        timestamp: "2024-01-15T19:35:00Z",
      },
      {
        id: "3",
        orderId: "1",
        status: "COOKING",
        message: "Pişiriliyor",
        timestamp: "2024-01-15T19:40:00Z",
      },
      {
        id: "4",
        orderId: "1",
        status: "OUT_FOR_DELIVERY",
        message: "Yolda",
        timestamp: "2024-01-15T19:50:00Z",
      },
      {
        id: "5",
        orderId: "1",
        status: "DELIVERED",
        message: "Teslim edildi",
        timestamp: "2024-01-15T20:05:00Z",
      },
    ],
  },
  {
    id: "2",
    orderNumber: "ADL-2024-002",
    userId: "1",
    status: "DELIVERED",
    totalAmount: 420,
    deliveryFee: 15,
    discountAmount: 0,
    paymentMethod: "Kredi Kartı",
    notes: null,
    estimatedTime: 30,
    addressId: "1",
    createdAt: "2024-01-12T20:15:00Z",
    updatedAt: "2024-01-12T20:50:00Z",
    items: [
      {
        id: "4",
        orderId: "2",
        productId: "2",
        quantity: 1,
        size: "Büyük",
        price: 220,
        notes: null,
      },
      {
        id: "5",
        orderId: "2",
        productId: "3",
        quantity: 1,
        size: "Orta",
        price: 250,
        notes: null,
      },
      {
        id: "6",
        orderId: "2",
        productId: "8",
        quantity: 2,
        size: "500ml",
        price: 25,
        notes: null,
      },
    ],
    tracking: [
      {
        id: "6",
        orderId: "2",
        status: "CONFIRMED",
        message: "Sipariş alındı",
        timestamp: "2024-01-12T20:15:00Z",
      },
      {
        id: "7",
        orderId: "2",
        status: "PREPARING",
        message: "Hazırlanıyor",
        timestamp: "2024-01-12T20:20:00Z",
      },
      {
        id: "8",
        orderId: "2",
        status: "COOKING",
        message: "Pişiriliyor",
        timestamp: "2024-01-12T20:25:00Z",
      },
      {
        id: "9",
        orderId: "2",
        status: "OUT_FOR_DELIVERY",
        message: "Yolda",
        timestamp: "2024-01-12T20:35:00Z",
      },
      {
        id: "10",
        orderId: "2",
        status: "DELIVERED",
        message: "Teslim edildi",
        timestamp: "2024-01-12T20:50:00Z",
      },
    ],
  },
  {
    id: "3",
    orderNumber: "ADL-2024-003",
    userId: "1",
    status: "DELIVERED",
    totalAmount: 350,
    deliveryFee: 15,
    discountAmount: 0,
    paymentMethod: "Kredi Kartı",
    notes: null,
    estimatedTime: 30,
    addressId: "1",
    createdAt: "2024-01-08T18:45:00Z",
    updatedAt: "2024-01-08T19:20:00Z",
    items: [
      {
        id: "7",
        orderId: "3",
        productId: "1",
        quantity: 3,
        size: "Küçük",
        price: 150,
        notes: null,
      },
      {
        id: "8",
        orderId: "3",
        productId: "9",
        quantity: 1,
        size: "1L",
        price: 25,
        notes: null,
      },
    ],
    tracking: [
      {
        id: "11",
        orderId: "3",
        status: "CONFIRMED",
        message: "Sipariş alındı",
        timestamp: "2024-01-08T18:45:00Z",
      },
      {
        id: "12",
        orderId: "3",
        status: "PREPARING",
        message: "Hazırlanıyor",
        timestamp: "2024-01-08T18:50:00Z",
      },
      {
        id: "13",
        orderId: "3",
        status: "COOKING",
        message: "Pişiriliyor",
        timestamp: "2024-01-08T18:55:00Z",
      },
      {
        id: "14",
        orderId: "3",
        status: "OUT_FOR_DELIVERY",
        message: "Yolda",
        timestamp: "2024-01-08T19:05:00Z",
      },
      {
        id: "15",
        orderId: "3",
        status: "DELIVERED",
        message: "Teslim edildi",
        timestamp: "2024-01-08T19:20:00Z",
      },
    ],
  },
  {
    id: "4",
    orderNumber: "ADL-2024-004",
    userId: "1",
    status: "DELIVERED",
    totalAmount: 195,
    deliveryFee: 15,
    discountAmount: 0,
    paymentMethod: "Kredi Kartı",
    notes: null,
    estimatedTime: 30,
    addressId: "1",
    createdAt: "2024-01-05T21:00:00Z",
    updatedAt: "2024-01-05T21:35:00Z",
    items: [
      {
        id: "9",
        orderId: "4",
        productId: "4",
        quantity: 1,
        size: "Orta",
        price: 200,
        notes: null,
      },
      {
        id: "10",
        orderId: "4",
        productId: "11",
        quantity: 1,
        size: "250ml",
        price: 12,
        notes: null,
      },
    ],
    tracking: [
      {
        id: "16",
        orderId: "4",
        status: "CONFIRMED",
        message: "Sipariş alındı",
        timestamp: "2024-01-05T21:00:00Z",
      },
      {
        id: "17",
        orderId: "4",
        status: "PREPARING",
        message: "Hazırlanıyor",
        timestamp: "2024-01-05T21:05:00Z",
      },
      {
        id: "18",
        orderId: "4",
        status: "COOKING",
        message: "Pişiriliyor",
        timestamp: "2024-01-05T21:10:00Z",
      },
      {
        id: "19",
        orderId: "4",
        status: "OUT_FOR_DELIVERY",
        message: "Yolda",
        timestamp: "2024-01-05T21:20:00Z",
      },
      {
        id: "20",
        orderId: "4",
        status: "DELIVERED",
        message: "Teslim edildi",
        timestamp: "2024-01-05T21:35:00Z",
      },
    ],
  },
  {
    id: "5",
    orderNumber: "ADL-2024-005",
    userId: "1",
    status: "DELIVERED",
    totalAmount: 480,
    deliveryFee: 15,
    discountAmount: 0,
    paymentMethod: "Kredi Kartı",
    notes: null,
    estimatedTime: 30,
    addressId: "1",
    createdAt: "2024-01-02T19:20:00Z",
    updatedAt: "2024-01-02T19:55:00Z",
    items: [
      {
        id: "11",
        orderId: "5",
        productId: "5",
        quantity: 2,
        size: "Büyük",
        price: 240,
        notes: null,
      },
      {
        id: "12",
        orderId: "5",
        productId: "7",
        quantity: 2,
        size: "1L",
        price: 25,
        notes: null,
      },
      {
        id: "13",
        orderId: "5",
        productId: "13",
        quantity: 1,
        size: "6 Adet",
        price: 45,
        notes: null,
      },
    ],
    tracking: [
      {
        id: "21",
        orderId: "5",
        status: "CONFIRMED",
        message: "Sipariş alındı",
        timestamp: "2024-01-02T19:20:00Z",
      },
      {
        id: "22",
        orderId: "5",
        status: "PREPARING",
        message: "Hazırlanıyor",
        timestamp: "2024-01-02T19:25:00Z",
      },
      {
        id: "23",
        orderId: "5",
        status: "COOKING",
        message: "Pişiriliyor",
        timestamp: "2024-01-02T19:30:00Z",
      },
      {
        id: "24",
        orderId: "5",
        status: "OUT_FOR_DELIVERY",
        message: "Yolda",
        timestamp: "2024-01-02T19:40:00Z",
      },
      {
        id: "25",
        orderId: "5",
        status: "DELIVERED",
        message: "Teslim edildi",
        timestamp: "2024-01-02T19:55:00Z",
      },
    ],
  },
]
